=== LauraTrcz/EDT-Stage/Edt_parser_solver_070621/parser_function_php/usp_timetabling_v0_1.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- Root element -->
<xs:element name="timetabling">
	<xs:complexType>
		<!-- Root elements -->
		<xs:sequence>
			<xs:element ref="calendar" minOccurs="0" maxOccurs="1" />
			<xs:element ref="rooms" minOccurs="0" maxOccurs="1" />
			<xs:element ref="equipments" minOccurs="0" maxOccurs="1" />
			<xs:element ref="teachers" minOccurs="0" maxOccurs="1" />
			<xs:element ref="groups" minOccurs="0" maxOccurs="1" />
			<xs:element ref="courses" minOccurs="1" maxOccurs="1" />
			<xs:element ref="constraints" minOccurs="0" maxOccurs="1" />
			<!-- TODO
			<xs:element ref="solution" minOccurs="0" maxOccurs="1" />
			-->
		</xs:sequence>
		
		<!-- Root attributes -->
		<xs:attribute ref="name" use="required" />
		<xs:attribute ref="nrWeeks" use="required" />
		<xs:attribute ref="daysPerWeek" use="required" />
		<xs:attribute ref="slotsPerDay" use="required" />
	</xs:complexType>
</xs:element>


<!-- Types -->
<xs:simpleType name="weekType"> <!-- 1-53 -->
	<xs:restriction base="xs:positiveInteger">
		<xs:maxInclusive value="53" />
	</xs:restriction>
</xs:simpleType>
<xs:simpleType name="weekDayType"> <!-- 1-7 -->
	<xs:restriction base="xs:positiveInteger">
		<xs:maxInclusive value="7" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="labelType"> <!-- token without comma -->
	<xs:restriction base="xs:token">
		<xs:pattern value="[^,]*" />
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="capacityType"> <!-- -1 or more -->
	<xs:restriction base="xs:integer">
		<xs:minInclusive value="-1"/>
	</xs:restriction>
</xs:simpleType>

<xs:simpleType name="sessionRoomsType">
	<xs:restriction base="xs:string">
	  <xs:enumeration value="none"/> <!-- No rooms are needed -->
	  <xs:enumeration value="single"/> <!-- Only one room per session (all the groups should fit in the room) -->
	  <xs:enumeration value="multiple"/> <!-- Pick as many rooms as necessary to fit the group sizes -->
	</xs:restriction>
</xs:simpleType>

<!-- Attributes -->
<!-- we want attributes with the same name to have the same definition among all the document -->

<!-- SHARED attributes -->
<!-- TODO: an `id` should be defined as a key in the element using it -->
<xs:attribute name="id" type="xs:string" /> <!-- Identifier (room, roomChain, equipment, teacher, group, course, part, class) -->

<!-- TODO: a `refId` should be defined as a refkey in the element using it -->
<xs:attribute name="refId" type="xs:string" /> <!-- Referenced identifier -->

<xs:attribute name="label" type="xs:string" /> <!-- Label of (room, equipment, teacher, group, course, part) -->

<xs:attribute name="name" type="xs:string" /> <!-- Name of the (instance, constraint, parameter) -->

<xs:attribute name="nrSessions" type="xs:positiveInteger" /> <!-- Number of sessions (in the part, that the teacher has to do) -->

<!-- TIMETABLING attributes -->
<xs:attribute name="nrWeeks" type="xs:positiveInteger" /> <!-- Number of weeks -->
<xs:attribute name="daysPerWeek" type="xs:positiveInteger" /> <!-- Number of days per week -->
<xs:attribute name="slotsPerDay" type="xs:positiveInteger" /> <!-- Number of slots per day -->

<!-- CALENDAR attributes -->
<xs:attribute name="duration" type="xs:positiveInteger" /> <!-- Duration (in minutes) of a slot -->

<!-- ROOMS attributes -->
<xs:attribute name="capacity" type="capacityType" /> <!-- Capacity of the room, can be `-1` meaning 'unlimited' -->

<!-- EQUIPMENTS attributes -->
<!-- TODO -->

<!-- TEACHERS attributes -->

<!-- GROUPS attributes -->
<xs:attribute name="size" type="xs:positiveInteger" /> <!-- Number of students in the group -->

<!-- COURSES attributes -->
<xs:attribute name="sessionLength" type="xs:positiveInteger" /> <!-- How many slots lasts a session -->
<xs:attribute name="sessionRooms" type="sessionRoomsType" /> <!-- How rooms for a session should be picked -->
<xs:attribute name="mandatory" type="xs:boolean" default="false" /> <!-- Should the room always be picked -->
<xs:attribute name="sessionTeachers" type="xs:nonNegativeInteger" /> <!-- How many teachers per session are required -->

<!-- CONSTRAINTS attributes -->
<xs:attribute name="groupBy" type="xs:string" /> <!-- How the scope should group the sessions -->
<xs:attribute name="sessionsMask" type="xs:string" /> <!-- How the sessions should be selected (printer-like notation: "1,3-6") -->
<xs:attribute name="type" type="xs:string" /> <!-- Type of the (constraint, parameter) -->
<xs:attribute name="attributeName" type="xs:Name" /> <!-- Name of the attribute targetted by the filter -->
<xs:attribute name="in" type="xs:string" /> <!-- Comma separated list of values -->
<xs:attribute name="notIn" type="xs:string" /> <!-- Comma separated list of values -->


<!-- CALENDAR elements -->
<xs:element name="calendar">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="startingDate" type="xs:date" />
			<xs:element name="weeks">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="week" type="weekType" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element> <!-- end of `weeks` -->
			<xs:element name="weekDays">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="weekDay" type="weekDayType" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element> <!-- end of `weekDays` -->
			<xs:element name="daySlots">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="daySlot" type="xs:string" maxOccurs="unbounded" />
						<!--<xs:element name="daySlot" type="xs:time" maxOccurs="unbounded" />-->
					</xs:sequence>
					<xs:attribute ref="duration" use="required" />
				</xs:complexType>
			</xs:element> <!-- end of `daySlots` -->
		</xs:sequence>
	</xs:complexType>
</xs:element>

<!-- ROOMS element -->
<xs:element name="rooms">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="roomList">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="room" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute ref="id" use="required" />
								<xs:attribute ref="capacity" use="required" />
								<xs:attribute ref="label" />
							</xs:complexType>
						</xs:element> <!-- end of `room` -->
					</xs:sequence>
				</xs:complexType>
			</xs:element> <!-- end of `roomList` -->
			<xs:element name="roomChains" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="roomChain" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="room" maxOccurs="unbounded">
										<xs:complexType>
											<xs:attribute ref="refId" use="required" />
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute ref="id" use="required" />
							</xs:complexType>
						</xs:element> <!-- end of `roomChain` -->
					</xs:sequence>
				</xs:complexType>
			</xs:element> <!-- end of `roomChains` -->
		</xs:sequence>
	</xs:complexType>
</xs:element>

<!-- TODO -->
<!-- EQUIPMENTS element -->
<xs:element name="equipments">
</xs:element>

<!-- TEACHERS element -->
<xs:element name="teachers">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="teacher" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute ref="id" use="required" />
					<xs:attribute ref="label" />
				</xs:complexType>
			</xs:element> <!-- end of `teacher`-->
		</xs:sequence>
	</xs:complexType>
</xs:element>

<!-- GROUPS element -->
<xs:element name="groups">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="group" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute ref="id" use="required" />
					<xs:attribute ref="size" use="required" />
					<xs:attribute ref="label" />
				</xs:complexType>
			</xs:element> <!-- end of `group`-->
		</xs:sequence>
	</xs:complexType>
</xs:element>

<!-- COURSES element -->
<xs:element name="courses">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="course" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="part" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="classes">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="class" maxOccurs="unbounded">
													<xs:complexType>
														<xs:sequence>
															<xs:element name="group" maxOccurs="unbounded">
																<xs:complexType>
																	<xs:attribute ref="refId" use="required" />
																</xs:complexType>
															</xs:element> <!-- end of `group` -->
														</xs:sequence>
														<xs:attribute ref="id" use="required" />
													</xs:complexType>
												</xs:element> <!-- end of `class` -->
											</xs:sequence>
										</xs:complexType>
									</xs:element> <!-- end of `classes` -->
									<xs:element name="equipments" minOccurs="0">
										<!-- TODO -->
									</xs:element> <!-- end of `equipments` -->
									<xs:element name="allowedRooms" minOccurs="0">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="room" maxOccurs="unbounded">
													<xs:complexType>
														<xs:attribute ref="refId" use="required" />
														<xs:attribute ref="mandatory" />
													</xs:complexType>
												</xs:element> <!-- end of `room` -->
											</xs:sequence>
											<xs:attribute ref="sessionRooms" use="required" />
										</xs:complexType>
									</xs:element> <!-- end of `allowedRooms` -->
									<xs:element name="allowedTeachers" minOccurs="0">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="teacher" maxOccurs="unbounded">
													<xs:complexType>
														<xs:attribute ref="refId" use="required" />
														<xs:attribute ref="nrSessions" use="required" />
													</xs:complexType>
												</xs:element> <!-- end of `teacher` -->
											</xs:sequence>
											<xs:attribute ref="sessionTeachers" use="required" />
										</xs:complexType>
									</xs:element> <!-- end of `allowedTeachers` -->
								</xs:sequence>
								<xs:attribute ref="id" use="required" />
								<xs:attribute ref="nrSessions" use="required" />
								<xs:attribute ref="sessionLength" use="required" />
								<xs:attribute ref="label" />
							</xs:complexType>
						</xs:element> <!-- end of `part` -->
					</xs:sequence>
					<xs:attribute ref="id" use="required" />
					<xs:attribute ref="label" />
				</xs:complexType>
			</xs:element> <!-- end of `course` -->
		</xs:sequence>
	</xs:complexType>
</xs:element>

<!-- CONSTRAINTS element -->
<xs:element name="constraints">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="constraintCollection" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="sessions" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="filter" minOccurs="0" maxOccurs="unbounded">
										<xs:complexType>
											<xs:attribute ref="type" use="required" />
											<xs:attribute ref="attributeName" use="required" />
											<xs:attribute ref="in" /> <!-- TODO: how to make sure that either `in` or `notIn` is there ? -->
											<xs:attribute ref="notIn" />
										</xs:complexType>
									</xs:element> <!-- end of `filter` -->
								</xs:sequence>
								<xs:attribute ref="groupBy" />
								<xs:attribute ref="sessionsMask" />
							</xs:complexType>
						</xs:element> <!-- end of `sessions` -->
						<xs:element name="constraint" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="parameters" minOccurs="0">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="parameter" maxOccurs="unbounded">
													<xs:complexType>
														<xs:simpleContent>
															<xs:extension base="xs:string">
																<xs:attribute ref="type" use="required" />
																<xs:attribute ref="name" use="required" />
															</xs:extension>
														</xs:simpleContent>
													</xs:complexType>
												</xs:element> <!-- end of `parameter` -->
											</xs:sequence>
										</xs:complexType>
									</xs:element> <!-- end of `parameters` -->
								</xs:sequence>
								<xs:attribute ref="name" use="required" />
								<xs:attribute ref="type" use="required" />
							</xs:complexType>
						</xs:element> <!-- end of `constraint` -->
					</xs:sequence>
				</xs:complexType>
			</xs:element> <!-- end of `constraintCollection` -->
		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== LauraTrcz/EDT-Stage/xml/ua_l3info_20s6_w12d5s8_e0r5t2g4_s44_dw.xml
<?xml version="1.0"?>
<timetabling xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="usp_timetabling_v0_1.xsd"
    name="ua_l3info_20s6_w12d5s8_e0r5t2g4_s44_dw" nrWeeks="12" daysPerWeek="5" slotsPerDay="8">
    <calendar>
        <startingYear>2021</startingYear>
        <weeks>
            <week>1</week>
            <week>2</week>
            <week>3</week>
            <week>4</week>
            <week>5</week>
            <week>6</week>
            <week>7</week>
            <week>8</week>
            <!-- semaine 9 : vacances-->
            <week>10</week>
            <week>11</week>
            <week>12</week>
            <week>13</week>
        </weeks>
        <weekDays>
            <weekDay>1</weekDay>
            <weekDay>2</weekDay>
            <weekDay>3</weekDay>
            <weekDay>4</weekDay>
            <weekDay>5</weekDay>
        </weekDays>
        <daySlotTimes duration="80">
            <daySlotTime>08:00:00</daySlotTime>
            <daySlotTime>09:30:00</daySlotTime>
            <daySlotTime>11:00:00</daySlotTime>
            <daySlotTime>12:30:00</daySlotTime>
            <daySlotTime>14:00:00</daySlotTime>
            <daySlotTime>15:30:00</daySlotTime>
            <daySlotTime>17:00:00</daySlotTime>
            <daySlotTime>18:30:00</daySlotTime>
        </daySlotTimes>
    </calendar>

    <!-- pas d'équipements déclarés -->
 
    <!-- une salle, réelle ou virtuelle, ne peut accueillir qu'une séance par créneau -->
    <!-- les plages de fermeture des salles se formulent par contraintes -->
    <!-- les profils de salles à capacité variable se formulent par contraintes -->
    <rooms>
	    <!-- `capacity` : capacité d'accueil maximum d'une salle en nombre d'étudiants -->
	        <!-- `capacity>=-1` -->
	        <!-- `capacity==1` : capacité illimitée -->
	    <!-- `label` (optionnel) : étiquette ou liste d'étiquettes quelconques pour une salle -->
	    <room id="AMPHI-A" capacity="90" label="BATIMENT-A"/>
	    <room id="AMPHI-B" capacity="286" label="BATIMENT-A"/>
	    <room id="H001" capacity="20" label="BATIMENT-H"/>
	    <room id="H002" capacity="42" label="BATIMENT-H"/>
	    <room id="H003" capacity="38" label="BATIMENT-H"/>
    </rooms>

    <!-- un enseignant ne peut dispenser qu'une séance par créneau -->
    <!-- les plages d'absences des enseignants se formulent par contraintes -->
    <teachers>
        <!-- `label` (optionnel) : étiquette ou liste d'étiquettes quelconques pour un enseignant -->
        <teacher id="LESAINT David" label="DEPARTEMENT-INFORMATIQUE"/>
        <teacher id="JAMIN Antoine" label="DEPARTEMENT-INFORMATIQUE"/>
    </teachers>

    <!-- un groupe ne peut assister qu'à une séance par créneau -->
    <!-- codification des options : (i = Images de synthèse, p = traitement de données en Python, q = Qt, s = Systèmes intelligents) -->
    <!-- les plages d'indisponibilité des groupes se formulent par contraintes -->
    <groups>
        <!-- `size` : nombre d'étudiants d'un groupe -->
            <!-- `size>=1` -->
        <!-- `label` (optionnel) : étiquette ou liste d'étiquettes quelconques pour un groupe -->
        <group id="1-td1-tp1-pq" size="18" label="L3-INFORMATIQUE,TD1,TP1" />
        <group id="2-td1-tp3-ps" size="22" label="L3-INFORMATIQUE,TD1,TP3" />
        <group id="3-td2-tp2-is" size="10" label="L3-INFORMATIQUE,TD2,TP2" />
        <group id="4-td2-tp2-qs" size="17" label="L3-INFORMATIQUE,TD2,TP2" />
    </groups>

    <courses>
        <!-- `label` (optionnel) : étiquette ou liste d'étiquettes quelconques pour un cours -->
        <course id="Développement-Web" label="L3-INFORMATIQUE,UE">
            <!-- les parties du cours -->
            <!-- au moins une partie par cours -->
            <!-- chaque partie comprend un ensemble de classes et prescrit un ensemble de ressources requises et possibles -->
            <!-- `nrSessions` : nombre de séances à dispenser pour chacune des classes de la partie -->
                <!-- `nrSessions>=1` -->
                <!-- chaque séance de classe est implicitement identifiée par un entier dans la plage `1..nrSessions` -->
            <!-- `sessionLength` : durée de chaque séance en nombre de créneaux consécutifs -->
            <!-- `sessionRooms` : mode de sélection d'une salle par session -->
            	<!-- `none` : pas de salle -->
            	<!-- `single` : une seule salle par session, toute la classe doit tenir dans la salle -->
            	<!-- `multiple` : autant de salles que nécessaire : les groupes d'une même classe pourront être dans des salles différentes -->
            <!-- `sessionTeachers` : nombre d'enseignants différents par séance -->
                <!-- `length>=1` -->
            <!-- `label` (optionnel) : étiquette ou liste d'étiquettes quelconques pour une partie -->
            <part id="Développement-Web-CM" nrSessions="12" sessionLength="1" label="CM">
                <!-- les classes de la partie et leurs groupes -->
                <!-- au moins une classe par partie, au moins un groupe par classe -->
                <!-- les classes de la partie partitionnent l'ensemble des groupes listés dans la partie -->
                <!-- les séances d'une classe sont chacune dispensées à tous les groupes de la classe -->
                <!-- les contraintes de programmation de séances se formulent par contraintes -->
                <classes>
                    <class id="Développement-Web-CM1">
                        <group refId="1-td1-tp1-pq" />
                        <group refId="2-td1-tp3-ps" />
                        <group refId="3-td2-tp2-is" />
                        <group refId="4-td2-tp2-qs" />
                    </class>
                </classes>

                <!-- pas d'équipements requis -->

                <!-- le pool de salles possibles ou requises pour toutes les classes -->
                <!-- la politique d'allocation de salles aux classes ou aux séances de classes se formule par contraintes -->
                    <!-- par exemple, placement d'une classe particulière dans une salle particulière -->
                    <!-- par exemple, placement des séances d'une classe dans la (les) même(s) salle(s) -->
                <allowedRooms sessionRooms="single">
                    <!-- `mandatory` (true|false) : (défaut: false) la salle doit-elle être utilisée obligatoirement -->
                    <room refId="AMPHI-A" />
                    <room refId="AMPHI-B" />
                </allowedRooms>

                <!-- le pool d'enseignants possibles ou requis pour les classes -->
                <!-- la politique d'attribution des classes ou séances de classes aux enseignants se formule par contraintes -->
                    <!-- par exemple, attribution d'une classe particulière à un enseignant particulier -->
                    <!-- par exemple, attribution des séances d'une classe au(x) même(s) enseignant(s) -->
                <allowedTeachers sessionTeachers="1">
                    <teacher refId="LESAINT David" nrSessions="12" />
                </allowedTeachers>
            </part>
 
            <part id="Développement-Web-TP" nrSessions="8" sessionLength="2" label="TP">
                <classes>
                    <class id="Développement-Web-TP1">
                        <group refId="1-td1-tp1-pq" />
                    </class>
                    <class id="Développement-Web-TP2">
                        <group refId="3-td2-tp2-is" />
                        <group refId="4-td2-tp2-qs" />
                    </class>
                    <class id="Développement-Web-TP3">
                        <group refId="2-td1-tp3-ps" />
                    </class>
                </classes>                
                
                <allowedRooms sessionRooms="single">
                    <room refId="H001" />
                    <room refId="H002" />
                    <room refId="H003" />
                </allowedRooms>
                
                <allowedTeachers sessionTeachers="1">
                    <teacher refId="LESAINT David" nrSessions="12" />
                    <teacher refId="JAMIN Antoine" nrSessions="12" />
                </allowedTeachers>
            </part>

            <part id="Développement-Web-PR" nrSessions="8" sessionLength="3" label="PR">
                <classes>
                    <class id="Développement-Web-PR1">
                        <group refId="1-td1-tp1-pq" />
                        <group refId="3-td2-tp2-is" />
                        <group refId="4-td2-tp2-qs" />
                        <group refId="2-td1-tp3-ps" />
                    </class>
                </classes>
                <allowedRooms sessionRooms="multiple">
                    <room refId="H001" />
                    <room refId="H002" />
                    <room refId="H003" />
                </allowedRooms>
                <!-- Pas d'enseignant pour les projets -->
            </part>
        </course>
    </courses>
    
    <constraints>
        <!-- les séances d'une classe du cours Développement-Web sont séquencées dans l'ordre conventionnel -->
        <constraintCollection>
            <!-- chaque portée regroupe les séances d'une classe du cours ciblé selon l'ordre conventionnel de leurs indices -->
            <sessions groupBy="class">
                <filter type="course" attributeName="id" in="Développement-Web"/>
            </sessions>
            <!-- chaque contrainte est dure -->
            <!-- le prédicat `sequenced` impose le séquencement (sans chevauchement) des séances qui se suivent dans sa portée -->
            <constraint name="sequenced" type="hard">
            </constraint> 
        </constraintCollection>

        <!-- les séances d'une classe de la partie Développement-Web-CM, à l'exclusion des séances 2 et 3, sont hebdomadaires et programmées sur le même créneau -->
        <constraintCollection>
